import type { VariableDefinition } from '@geoeye/types'

export const CORE_VARIABLES = [
  {
    key: 'structure.alpha',
    displayName: 'Alpha',
    description: 'Acute angle between the feature trace and the core axis.',
    dataType: 'numeric',
    canonicalUnit: 'deg',
    origin: 'primary',
    spatialSupport: 'orientation',
    compatibleAnalyses: ['structure.alpha_beta_conversion', 'structure.stereonet'],
  },
  {
    key: 'structure.beta',
    displayName: 'Beta',
    description: 'Rotation angle around the oriented core reference line.',
    dataType: 'numeric',
    canonicalUnit: 'deg',
    origin: 'primary',
    spatialSupport: 'orientation',
    compatibleAnalyses: ['structure.alpha_beta_conversion', 'structure.stereonet'],
  },
  {
    key: 'structure.type',
    displayName: 'Structure type',
    description: 'Dictionary-backed classification assigned to a structural observation.',
    dataType: 'category',
    canonicalUnit: null,
    origin: 'primary',
    spatialSupport: 'orientation',
    compatibleAnalyses: ['structure.stereonet', 'structure.summary', 'structure.domains'],
  },
  {
    key: 'structure.apparent_angle',
    displayName: 'Apparent angle',
    description: 'Feature angle measured on the row image by GeoEye Field.',
    dataType: 'numeric',
    canonicalUnit: 'deg',
    origin: 'primary',
    spatialSupport: 'orientation',
    compatibleAnalyses: ['structure.quality_control'],
  },
  {
    key: 'structure.true_dip',
    displayName: 'True dip',
    description: 'True dip derived from an oriented observation and drillhole orientation.',
    dataType: 'numeric',
    canonicalUnit: 'deg',
    origin: 'derived',
    spatialSupport: 'orientation',
    compatibleAnalyses: ['structure.stereonet', 'structure.joint_sets'],
  },
  {
    key: 'structure.true_dip_direction',
    displayName: 'True dip direction',
    description: 'Dip direction derived from an oriented observation and drillhole orientation.',
    dataType: 'numeric',
    canonicalUnit: 'deg',
    origin: 'derived',
    spatialSupport: 'orientation',
    compatibleAnalyses: ['structure.stereonet', 'structure.joint_sets'],
  },
  {
    key: 'structure.joint_set',
    displayName: 'Joint set',
    description: 'Algorithmic joint-set population membership.',
    dataType: 'category',
    canonicalUnit: null,
    origin: 'derived',
    spatialSupport: 'orientation',
    compatibleAnalyses: ['structure.joint_sets', 'structure.domains'],
  },
  {
    key: 'joint.aperture',
    displayName: 'Joint aperture',
    description: 'Observed opening width of a joint.',
    dataType: 'numeric',
    canonicalUnit: 'mm',
    origin: 'primary',
    spatialSupport: 'point',
    compatibleAnalyses: ['geotechnical.rmr', 'structure.summary'],
  },
  {
    key: 'joint.roughness',
    displayName: 'Joint roughness',
    description: 'Observed roughness classification of a joint surface.',
    dataType: 'category',
    canonicalUnit: null,
    origin: 'primary',
    spatialSupport: 'point',
    compatibleAnalyses: ['geotechnical.rmr', 'structure.summary'],
  },
  {
    key: 'geotech.rqd',
    displayName: 'RQD',
    description: 'Rock Quality Designation over a logged interval.',
    dataType: 'numeric',
    canonicalUnit: '%',
    origin: 'primary',
    spatialSupport: 'interval',
    compatibleAnalyses: ['geotechnical.rqd', 'geotechnical.rmr'],
  },
  {
    key: 'geotech.ucs',
    displayName: 'UCS',
    description: 'Uniaxial compressive strength measurement.',
    dataType: 'numeric',
    canonicalUnit: 'MPa',
    origin: 'primary',
    spatialSupport: 'interval',
    compatibleAnalyses: ['geotechnical.rmr', 'geotechnical.domains'],
  },
  {
    key: 'geotech.rmr76',
    displayName: 'RMR76',
    description: '1976 Bieniawski Rock Mass Rating.',
    dataType: 'numeric',
    canonicalUnit: null,
    origin: 'derived',
    spatialSupport: 'interval',
    compatibleAnalyses: ['geotechnical.rmr', 'geotechnical.domains'],
    metadata: { method: 'Bieniawski 1976', scoreType: 'bounded_ordinal_score' },
  },
  {
    key: 'geotech.rmr76_class',
    displayName: 'RMR76 class',
    description: 'Rock-mass class derived from the 1976 Bieniawski Rock Mass Rating.',
    dataType: 'category',
    canonicalUnit: null,
    origin: 'derived',
    spatialSupport: 'interval',
    compatibleAnalyses: ['geotechnical.rmr', 'geotechnical.domains', 'domain'],
    metadata: { method: 'Bieniawski 1976', sourceVariable: 'geotech.rmr76' },
  },
  {
    key: 'geotech.rmr90',
    displayName: 'RMR90',
    description: '1990 Laubscher in-situ Rock Mass Rating before mining adjustments.',
    dataType: 'numeric',
    canonicalUnit: null,
    origin: 'derived',
    spatialSupport: 'interval',
    compatibleAnalyses: ['geotechnical.rmr', 'geotechnical.mrmr', 'geotechnical.domains'],
  },
  {
    key: 'geotech.mrmr90',
    displayName: 'MRMR90',
    description: 'Laubscher Mining Rock Mass Rating after weathering, orientation, stress, and blasting adjustments.',
    dataType: 'numeric',
    canonicalUnit: null,
    origin: 'derived',
    spatialSupport: 'interval',
    compatibleAnalyses: ['geotechnical.mrmr', 'geotechnical.domains'],
  },
  {
    key: 'geotech.q',
    displayName: 'Q-system index',
    description: 'Barton tunnelling quality index calculated from RQD, Jn, Jr, Ja, Jw, and SRF.',
    dataType: 'numeric',
    canonicalUnit: null,
    origin: 'derived',
    spatialSupport: 'interval',
    compatibleAnalyses: ['geotechnical.q', 'geotechnical.domains'],
  },
  {
    key: 'assay.au',
    displayName: 'Gold',
    description: 'Gold assay concentration.',
    dataType: 'numeric',
    canonicalUnit: 'g/t',
    origin: 'integrated',
    spatialSupport: 'interval',
    compatibleAnalyses: ['explore', 'grade', 'variography', 'domain'],
  },
  {
    key: 'assay.cu',
    displayName: 'Copper assay',
    description: 'Copper assay concentration.',
    dataType: 'numeric',
    canonicalUnit: '%',
    origin: 'integrated',
    spatialSupport: 'interval',
    compatibleAnalyses: ['explore', 'grade', 'variography', 'domain'],
  },
  {
    key: 'xrf.cu',
    displayName: 'Copper XRF',
    description: 'Copper concentration reported by an XRF integration.',
    dataType: 'numeric',
    canonicalUnit: 'ppm',
    origin: 'integrated',
    spatialSupport: 'point',
    compatibleAnalyses: ['explore', 'multivariate', 'domain'],
  },
] as const satisfies readonly VariableDefinition[]
